/* Shared experience for the static demo and authenticated home server. */
(async () => {
  'use strict';
  const api=window.SaiDemoAPI,engine=window.SajuInsights,$=id=>document.getElementById(id);
  let startupError;try{await api.ready;}catch(e){startupError=e;}
  const names={kakao:'카카오',naver:'네이버',google:'구글'};
  const art={saju:'📖',compatibility:'💞',decade:'🌳',annual:'🌙',dates:'📅',daily:'☀️',consult:'💬'};
  const groups={자율:['🌱','나만의 길'],표현:['✨','표현의 힘'],자원:['🍯','생활의 감각'],책임:['🧭','약속의 힘'],학습:['🔮','깊은 시선']};
  let dialogRevision=0,pending=null,activeProduct=null,currentResult=null,shareTitle='사이 · 나를 알아가는 사주',shareCaption='나를 이해하는 작은 발견, 사이에서 함께해요.',returnFocus=null;
  const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;};
  const append=(p,tag,cls,text)=>{const n=el(tag,cls,text);p.append(n);return n;};
  const button=(p,text,fn,cls='button')=>{const b=append(p,'button',cls,text);b.type='button';b.addEventListener('click',()=>run(fn));return b;};
  const run=fn=>Promise.resolve().then(fn).catch(e=>notify(e.message||'다시 시도해주세요.'));
  const status=el('div','sai-toast');status.id='saiStatus';status.setAttribute('role','status');status.setAttribute('aria-live','polite');document.body.append(status);let noticeTimer;
  function notify(message){status.textContent=message;status.classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>status.classList.remove('visible'),6500);const error=$('experienceError');if(error)error.textContent=message;}
  const modal=el('dialog','experience-dialog');modal.id='experienceDialog';modal.setAttribute('aria-labelledby','experienceTitle');
  modal.innerHTML='<div class="experience-inner"><div class="experience-heading"><h2 id="experienceTitle"></h2><button type="button" class="detail-close" id="experienceClose">닫기 ×</button></div><div id="experienceBody"></div><p id="experienceError" class="error" role="alert"></p></div>';
  document.body.append(modal);$('experienceClose').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close();});modal.addEventListener('close',()=>{pending=null;returnFocus?.focus?.();});
  function dialog(title){dialogRevision++;if(!modal.open)returnFocus=document.activeElement;$('experienceTitle').textContent=title;$('experienceError').textContent='';const body=$('experienceBody');body.replaceChildren();if(!modal.open)modal.showModal();return body;}
  const session=()=>api.session();
  function needLogin(fn){if(session())return fn();pending=fn;login();}
  function login(){const body=dialog('반가워요, 사이에 오신 걸 환영해요');const img=append(body,'img','welcome-mascot');img.src='./assets/sai-mascot.png';img.alt='책을 펼쳐 반기는 사이 토끼';append(body,'p','',api.production?'카카오 또는 네이버 계정으로 로그인해 운세와 상담을 보관하세요.':'테스트 로그인으로 무료 운세와 상담을 만나보세요. 실제 소셜 계정 인증이나 개인정보 전송은 없습니다.');
    for(const provider of (api.production?['kakao','naver']:Object.keys(names)))button(body,`${names[provider]}로 ${api.production?'로그인':'테스트 로그인'}`,async()=>{await api.login(provider);if(api.production)return;updateAccount();restoreProfile();const next=pending;pending=null;if(next)next();else accountPage();},`social-login ${provider}`);
    button(body,'돌아가기',()=>modal.close(),'text-button');
  }
  function updateAccount(){const a=session();$('saiLogin').textContent=a?'마이페이지':'로그인';$('dailyCaption').textContent=a?'오늘의 이야기를 열어보세요':'로그인하고 매일 무료로';$('consultCaption').textContent=a?.consults[api.today()]?'오늘의 상담 다시 보기':'하루 한 번, 고민을 나눠요';}
  function restoreProfile(){const input=session()?.profile;if(!input)return;const form=$('manseForm');for(const [k,v] of Object.entries(input)){const n=form.elements[k];if(n){if(n.type==='checkbox')n.checked=v;else n.value=v;}}$('leapField').hidden=input.calendar!=='lunar';try{window.currentSajuChart=window.calculateStaticManse(input);}catch{window.currentSajuChart=null;}}
  function chart(){const c=window.currentSajuChart;if(!c)throw new Error('먼저 생년월일시로 만세력을 만들어주세요.');return c;}
  function needChart(fn){if(window.currentSajuChart)return fn();modal.close();notify('아래에서 만세력을 만든 뒤 선택한 서비스를 다시 열어주세요.');$('start').scrollIntoView({behavior:'smooth'});$('manseForm').elements.date.focus();}
  function accountPage(){const a=session();if(!a)return login();const body=dialog('나의 사이');append(body,'p','demo-label',api.production?'내 계정 · 서버에 저장':'테스트 계정 · 이 브라우저에만 저장');append(body,'h3','',a.name);append(body,'p','',`연결된 방식: ${a.providers.map(p=>names[p]).join(' · ')}`);
    const links=append(body,'div','row-actions');for(const p of (api.production?['kakao','naver']:Object.keys(names))){const b=button(links,a.providers.includes(p)?`${names[p]} 연결됨`:`${names[p]} 연동하기`,async()=>{await api.link(p);if(!api.production)accountPage();});b.disabled=a.providers.includes(p);}
    append(body,'h3','','내 출생 정보');append(body,'p','',a.profile?`${a.profile.nickname||'나'} · ${a.profile.date} · ${a.profile.time||'시간 모름'}`:'저장된 출생 정보가 없어요.');
    button(body,'출생 정보 수정',()=>{modal.close();$('start').scrollIntoView({behavior:'smooth'});$('manseForm').elements.date.focus();},'text-button');
    append(body,'h3','','오늘의 이용 내역');const daily=a.daily[api.today()],consult=a.consults[api.today()];
    if(daily)button(body,'오늘의 무료 운세 다시 보기',()=>showDaily(daily),'text-button');else append(body,'p','','무료 운세를 아직 열지 않았어요.');
    if(consult)button(body,'오늘의 상담 다시 보기',()=>showConsult(consult),'text-button');else append(body,'p','','오늘의 무료 상담 1회가 남아 있어요.');
    append(body,'h3','','구매 보관함');if(!a.orders.length)append(body,'p','','아직 구매한 이야기가 없어요.');
    for(const o of a.orders)button(body,`${api.products[o.product]} · 990원 테스트 · ${new Date(o.createdAt).toLocaleDateString('ko-KR')}`,()=>showProductResult(o.result),'history-button');
    button(body,'로그아웃',async()=>{await api.logout();window.currentSajuChart=null;resetVisible();updateAccount();modal.close();},'text-button');
    button(body,api.production?'계정과 저장 정보 삭제':'이 브라우저의 테스트 데이터 모두 삭제',confirmReset,'text-button danger');
  }
  function resetVisible(){$('output').hidden=true;$('manseForm').reset();$('leapField').hidden=true;const n=$('personalityStory');if(n)n.remove();}
  function confirmReset(){const body=dialog(api.production?'계정 삭제':'테스트 데이터 삭제');append(body,'p','',api.production?'계정, 출생 정보, 상담 기록을 서버에서 삭제합니다. 다시 로그인하면 새 계정이 만들어집니다.':'이 브라우저에 저장한 모든 테스트 계정, 출생 정보, 상담, 구매 내역을 삭제합니다.');button(body,'모두 삭제',async()=>{await api.reset();window.currentSajuChart=null;resetVisible();updateAccount();modal.close();notify(api.production?'계정과 저장 정보를 삭제했어요.':'테스트 데이터를 삭제했어요.');});button(body,'취소',()=>modal.close(),'text-button');}
  const nav=document.querySelector('.nav nav');const servicesLink=append(nav,'a','','운세 메뉴');servicesLink.href='#services';const faqLink=append(nav,'a','','FAQ');faqLink.href='#faq';
  const loginButton=el('button','nav-cta','로그인');loginButton.id='saiLogin';loginButton.type='button';document.querySelector('.nav').insertBefore(loginButton,$('themeToggle'));loginButton.addEventListener('click',()=>run(()=>session()?accountPage():login()));
  const services=el('section','section service-section');services.id='services';services.innerHTML='<div class="section-head"><span class="kicker">SAI · LITTLE DISCOVERIES</span><h2>오늘의 나에게,<br><em>어떤 이야기가 필요해요?</em></h2><p>가볍게 펼쳐보고, 나에게 남는 한 문장을 찾아보세요.</p><span class="demo-label">테스트 체험 · 실제 결제 0원</span></div><div class="free-services" id="freeServices"></div><div class="product-grid" id="productGrid"></div>';
  document.querySelector('.band').after(services);
  for(const [id,title,caption] of [['daily','오늘의 무료 운세','로그인하고 매일 무료로'],['consult','오늘의 사주 상담','하루 한 번, 고민을 나눠요']]){
    const b=button($('freeServices'),' ',()=>needLogin(()=>needChart(()=>id==='daily'?daily():consultation())),`free-card ${id}`);b.replaceChildren();append(b,'span','free-emoji',art[id]).setAttribute('aria-hidden','true');const text=append(b,'span','');append(text,'strong','',title);const small=append(text,'small','',caption);small.id=id==='daily'?'dailyCaption':'consultCaption';append(b,'span','free-pill','FREE ↗');}
  const descriptions={saju:'나를 닮은 이야기 한 권',compatibility:'다른 두 사람이 만나는 방식',decade:'내 삶의 긴 흐름을 읽어요',annual:'한 해의 주제와 열두 달',dates:'중요한 날, 후보를 함께 골라요'};
  for(const [id,title] of Object.entries(api.products)){
    const b=button($('productGrid'),' ',()=>needChart(()=>product(id)),`product-card product-${id}`);b.replaceChildren();const visual=append(b,'span','product-art');const img=append(visual,'img','product-mascot');img.src=id==='compatibility'?'./assets/sai-companions.png':id==='dates'||id==='annual'?'./assets/sai-seasons.png':'./assets/sai-mascot.png';img.alt='';img.loading='lazy';img.width=320;img.height=320;append(visual,'span','product-symbol',art[id]).setAttribute('aria-hidden','true');append(b,'strong','',`990원 ${title}`);append(b,'small','',descriptions[id]);append(b,'span','product-arrow','이야기 열기 ↗');}
  function renderText(body,result){for(const p of result.paragraphs||[])append(body,'p','reading-paragraph',p);if(result.items?.length){const details=append(body,'details','evidence-box');append(details,'summary','','해석 근거 보기');const list=append(details,'ul','');result.items.forEach(i=>append(list,'li','',i));}}
  async function daily(){if(!api.production){showDaily(await api.daily(chart()));updateAccount();return;}const c=chart(),body=dialog('오늘의 이야기를 준비하고 있어요');const loading=window.SaiLoading.mount(body,{kind:'daily',label:'오늘, 나에게 필요한 이야기를 준비하고 있어요.'});const revision=dialogRevision;try{const result=await api.daily(c,text=>{if(revision===dialogRevision&&modal.open)loading.updateText(text);});updateAccount();if(revision===dialogRevision&&modal.open)showDaily(result);}catch(e){if(revision!==dialogRevision||!modal.open)return;const body=dialog('오늘의 운세를 받지 못했어요');append(body,'p','error',e.message);button(body,'다시 시도',daily);}finally{loading.dispose();}}
  function showDaily(result){const body=dialog('오늘의 무료 운세');append(body,'span','reading-emoji','☀️');append(body,'p','eyebrow',`${result.day} · 한국 시간`);append(body,'h3','',result.title);renderText(body,{paragraphs:result.paragraphs,items:result.evidence});append(body,'p','form-note','오늘 처음 만든 운세를 하루 동안 다시 보여드려요. 출생 정보를 바꿔도 오늘의 운세는 유지됩니다.');button(body,'오늘의 문장 공유하기',()=>share(result.title,result.paragraphs.at(-1)));}
  function consultation(){const saved=session().consults[api.today()];if(saved)return showConsult(saved);const body=dialog('오늘의 사주 상담');append(body,'span','reading-emoji','💬');append(body,'p','','지금 가장 마음에 걸리는 한 가지를 들려주세요.');append(body,'p','form-note',api.production?'하루 1회 무료 · 한국 시간 자정에 갱신 · 고민을 함께 살펴보는 시간':'하루 1회 무료 · 한국 시간 자정에 갱신 · 테스트 상담은 주제별 규칙으로 답해요.');const form=append(body,'form','consult-form');const label=append(form,'label','','나누고 싶은 고민');const textarea=append(label,'textarea','');textarea.name='question';textarea.required=true;textarea.minLength=5;textarea.maxLength=500;textarea.rows=4;textarea.placeholder='예: 이직을 고민 중인데 어떤 업무 방식이 나와 맞을까요?';const samples=append(form,'div','question-chips');for(const q of ['연애에서 제 마음을 어떻게 표현하면 좋을까요?','이직할 때 어떤 업무 방식을 살펴볼까요?','돈을 쓸 때 반복되는 습관이 궁금해요.'])button(samples,q,()=>textarea.value=q,'chip');const submit=append(form,'button','button','무료 상담 받기');submit.type='submit';form.addEventListener('submit',e=>{e.preventDefault();if(submit.disabled)return;submit.disabled=true;submit.textContent='고민을 살펴보고 있어요…';const revision=dialogRevision,loading=api.production?window.SaiLoading.mount(body,{kind:'consult',label:'들려주신 고민을 차근차근 살펴보고 있어요.'}):null;run(async()=>{try{const result=await api.consultation(chart(),textarea.value,text=>{if(revision===dialogRevision&&modal.open)loading?.updateText(text);});updateAccount();if(revision===dialogRevision&&modal.open)showConsult(result);}finally{loading?.dispose();submit.disabled=false;submit.textContent='무료 상담 받기';}});});}
  function showConsult(result){const body=dialog(`${result.category} 상담`);append(body,'span','reading-emoji','💬');renderText(body,result);if(!result.consumes&&result.consumes!==undefined){append(body,'p','form-note','무료 상담은 차감되지 않았어요.');button(body,'고민 다시 적기',consultation);}else append(body,'p','form-note','오늘의 상담은 마이페이지에서 다시 볼 수 있어요. 내일 새로운 상담 1회가 열립니다.');}
  function field(form,label,name,type='text',value=''){const l=append(form,'label','field-label',label),i=append(l,'input','');i.name=name;i.type=type;i.value=value;return i;}
  function select(form,label,name,options,value){const l=append(form,'label','field-label',label),s=append(l,'select','');s.name=name;for(const [v,t] of options){const o=append(s,'option','',t);o.value=v;}if(value)s.value=value;return s;}
  function product(id){activeProduct=id;const body=dialog(`${api.production?'나의':'990원'} ${api.products[id]}`),c=chart();append(body,'span','reading-emoji',art[id]);append(body,'p','',descriptions[id]);append(body,'p','demo-label',api.production?'나를 알아가는 이야기 · 현재 무료 제공':'상품 가격 990원 · 테스트 청구액 0원');append(body,'p','form-note',`분석 대상: ${c.input.nickname||'나'} · ${c.input.date} · ${c.input.time||'시간 모름'}`);
    const form=append(body,'form','product-form');
    if(id==='compatibility'){
      append(form,'h3','','함께 볼 사람');append(form,'p','form-note','상대방과 동의한 정보로 살펴보세요.');field(form,'이름 (선택)','nickname').placeholder='예: 이다온';select(form,'달력','calendar',[['solar','양력'],['lunar','음력']]);const leap=field(form,'음력 윤달','leapMonth','checkbox');leap.value='on';const date=field(form,'생년월일','date','text');date.required=true;date.placeholder='예: 20010321';date.inputMode='numeric';field(form,'출생 시각 (모르면 비우기)','time').placeholder='예: 1530';select(form,'대운 계산 기준','gender',[['','선택 안 함'],['male','남성 기준'],['female','여성 기준']]);select(form,'두 사람의 관계','relation',[['연인','연인·썸'],['친구','친구'],['가족','가족'],['동료','동료']]);
    }
    if(id==='annual'){const y=field(form,'보고 싶은 연도','year','number',api.today().slice(0,4));y.min=1900;y.max=2100;y.required=true;}
    if(id==='dates'){select(form,'날짜를 고르는 목적','purpose',[['meeting','만남'],['wedding','결혼'],['move','이사'],['work','일·프로젝트 시작']]);const now=api.today();field(form,'시작일','start','date',now).required=true;const until=new Date(now+'T00:00:00Z');until.setUTCDate(until.getUTCDate()+29);field(form,'종료일 (최대 90일)','end','date',until.toISOString().slice(0,10)).required=true;}
    const submit=append(form,'button','button',api.production?'이야기 펼쳐보기':'무료 미리보기');submit.type='submit';form.addEventListener('submit',e=>{e.preventDefault();if(submit.disabled)return;submit.disabled=true;run(async()=>{try{const params=Object.fromEntries(new FormData(form));if(id==='compatibility')params.leapMonth=form.elements.leapMonth.checked;await preview(id,c,params);}finally{submit.disabled=false;}});});
  }
  function buildProduct(id,c,params){const [year,month]=api.today().split('-').map(Number),report=engine.full(c,{year,month});
    if(id==='saju')return {title:'나의 사주 이야기',paragraphs:report.overview.slice(0,3),sections:report.sections};
    if(id==='compatibility'){const other=window.calculateStaticManse({...params,relationshipStatus:'',leapMonth:params.calendar==='lunar'&&params.leapMonth});return engine.compatibility(c,other,params.relation);}
    if(id==='decade'){if(!c.luck)throw new Error('대운은 출생 시각과 대운 계산 기준이 필요해요. 기존 입력란에서 두 항목을 채워주세요.');return {title:'나의 대운 이야기',paragraphs:[`${engine.profile(c).top[0].title}인 나의 긴 흐름`],sections:[report.sections[1],report.sections[9],report.sections[11]]};}
    if(id==='annual'){const y=Number(params.year),f=engine.frame(c,y);return {title:`${y}년의 나`,paragraphs:[f.theme.title,f.tension,f.theme.action],items:f.evidence,sections:Array.from({length:12},(_,i)=>{const m=engine.frame(c,y,i+1);return {title:`${i+1}월 · ${m.theme.group}`,paragraphs:engine.domain(m,'일·사업',c.input.relationshipStatus),items:m.evidence};})};}
    const candidates=engine.dates(c,params.start,params.end,params.purpose);return {title:'나에게 맞춰 살펴볼 날짜',paragraphs:['원국과 각 날짜의 간지 관계를 비교한 참고 후보입니다. 실제 일정과 준비 조건을 함께 확인하세요. 동점은 빠른 날짜 순입니다.'],sections:candidates.map(d=>({title:`${d.date} · ${d.theme}`,paragraphs:[d.reason,d.action],items:[]}))};
  }
  async function preview(id,c,params){if(api.production){const body=dialog(`${api.products[id]} 이야기를 준비하고 있어요`);const loading=window.SaiLoading.mount(body,{kind:id,label:'나에게 맞는 이야기를 준비하고 있어요.'});const revision=dialogRevision;try{const other=id==='compatibility'?{calendar:params.calendar,date:params.date,time:params.time,gender:params.gender,leapMonth:!!params.leapMonth}:undefined;const result=await api.reading(id,c,{...params,...(other?{other}:{})},text=>{if(revision===dialogRevision&&modal.open)loading.updateText(text);});if(revision===dialogRevision&&modal.open)showProductResult(result,{kind:id,chart:c,params:{...params,...(other?{other}:{})}});}catch(e){if(revision!==dialogRevision||!modal.open)return;const body=dialog('이야기를 불러오지 못했어요');append(body,'p','error',e.message);button(body,'다시 시도',()=>preview(id,c,params));}finally{loading.dispose();}return;}const result=buildProduct(id,c,params),existing=api.findOrder(id,c,params);if(existing)return showProductResult(existing.result);const body=dialog(`${api.products[id]} 미리보기`);append(body,'span','reading-emoji',art[id]);append(body,'h3','',result.title);append(body,'p','',result.paragraphs[0]);append(body,'p','preview-note',`이어서 ${result.sections?result.sections.length+'개 이야기':'두 사람의 차이와 실천 방법'}를 만나보세요.`);button(body,'990원 테스트 구매',()=>needLogin(()=>checkout(id,c,params,result)));button(body,'입력 바꾸기',()=>product(id),'text-button');}
  function checkout(id,c,params,result){const existing=api.findOrder(id,c,params);if(existing)return showProductResult(existing.result);const body=dialog('주문 확인');append(body,'h3','',`990원 ${api.products[id]}`);append(body,'p','',result.title);append(body,'p','demo-label','정가 990원 · 실제 청구 0원');append(body,'p','','이 주문은 테스트입니다. 카드나 계좌 정보를 입력하지 않습니다.');const row=append(body,'div','row-actions');button(row,'테스트 구매 완료',()=>{const o=api.purchase(id,c,params,result);showProductResult(o.result);updateAccount();});button(row,'취소',()=>preview(id,c,params),'text-button');const details=append(body,'details','evidence-box');append(details,'summary','','실패 상황 테스트');button(details,'결제 실패 시뮬레이션',()=>api.purchase(id,c,params,result,'failure'),'text-button');}
  function showProductResult(result,context){currentResult=result;const body=dialog(result.title);append(body,'span','reading-emoji','✨');append(body,'p','demo-label',api.production?'나를 알아가는 작은 발견':'테스트 구매 완료 · 보관함에 저장됨');renderText(body,result);for(const section of result.sections||[]){const d=append(body,'details','product-section');append(d,'summary','',section.title);if(section.lazy&&context){const content=append(d,'div','');let job;const revision=dialogRevision;const load=async()=>{if(job)return;const loading=window.SaiLoading.mount(content,{kind:'section',label:`${section.title} 이야기를 준비하고 있어요.`});job=api.reading('section',context.chart,{...context.params,reportKind:context.kind,section:section.index},text=>{if(revision===dialogRevision&&modal.open)loading.updateText(text);});try{const answer=await job;if(revision!==dialogRevision||!modal.open)return;content.replaceChildren();renderText(content,answer);}catch(e){job=null;if(revision!==dialogRevision||!modal.open)return;content.replaceChildren();append(content,'p','error',e.message);button(content,'다시 작성',load);}finally{loading.dispose();}};d.addEventListener('toggle',()=>{if(d.open)load();});}else renderText(d,section);}button(body,'이야기 공유하기',()=>share(result.title,result.paragraphs?.[0]||'나를 알아가는 작은 발견'));}
  function publicURL(){return location.protocol==='http:'||location.protocol==='https:'?`${location.origin}${location.pathname}`:'https://tns7gus-tech.github.io/Saju/';}
  async function copyText(text){if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return;}const area=el('textarea');area.value=text;modal.append(area);area.select();const ok=document.execCommand('copy');area.remove();if(!ok)throw new Error('복사하지 못했어요. 아래 공유 문장을 직접 선택해 복사해주세요.');}
  async function shareImage(){const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d');ctx.fillStyle='#f6f2eb';ctx.fillRect(0,0,1080,1350);const img=new Image();img.src='./assets/sai-mascot.png';await img.decode();ctx.drawImage(img,250,80,580,580);ctx.fillStyle='#405b46';ctx.textAlign='center';ctx.font='bold 42px sans-serif';ctx.fillText('사이 · 나의 작은 발견',540,740);ctx.font='32px sans-serif';const text=shareCaption.slice(0,180);let line='',lines=[];for(const char of text){if(ctx.measureText(line+char).width>860){lines.push(line);line=char;}else line+=char;}if(line)lines.push(line);lines.slice(0,8).forEach((l,i)=>ctx.fillText(l,540,840+i*48));ctx.font='24px sans-serif';ctx.fillText('SAI · 사주로 시작하는 사이',540,1280);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('이미지를 만들지 못했습니다.');return blob;}
  function download(blob){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='sai-story.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function share(title=shareTitle,caption=shareCaption){shareTitle=title;shareCaption=caption;const body=dialog('나의 이야기 공유하기');append(body,'p','','공유 문장과 이미지에는 이름·생년월일·출생시각이 들어가지 않아요. 게시 전에 내용을 확인하세요.');append(body,'blockquote','share-preview',caption);const url=publicURL(),text=`${title}\n${caption}\n${url}`;const row=append(body,'div','share-options');
    const link=(label,href)=>{const a=append(row,'a','button',label);a.href=href;a.target='_blank';a.rel='noopener noreferrer';};
    link('𝕏에 공유',`https://twitter.com/intent/tweet?text=${encodeURIComponent(title+'\n'+caption)}&url=${encodeURIComponent(url)}`);
    link('네이버 블로그',`https://share.naver.com/web/shareView?url=${encodeURIComponent(url)}&title=${encodeURIComponent(title+' · '+caption)}`);
    button(row,'인스타그램용 이미지',async()=>{const blob=await shareImage(),file=new File([blob],'sai-story.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})&&navigator.share){try{await navigator.share({files:[file],title,text:caption});}catch(e){if(e.name!=='AbortError')throw e;}}else{download(blob);await copyText(caption);notify('이미지를 저장하고 문장을 복사했어요. 인스타그램에서 직접 게시해주세요.');}},'button');
    button(row,'공유 문장 복사',async()=>{await copyText(text);notify('공유 문장을 복사했어요.');});button(row,'링크 복사',async()=>{await copyText(url);notify('링크를 복사했어요.');});button(row,'이미지 저장',async()=>download(await shareImage()));
    if(navigator.share)button(row,'다른 앱으로 공유',async()=>{try{await navigator.share({title,text:caption,url});}catch(e){if(e.name!=='AbortError')throw e;}});
    append(body,'p','form-note','인스타그램은 지원 기기의 공유 메뉴에서 선택하거나, 저장한 이미지를 직접 올릴 수 있어요.');
  }
  const shareButton=button(document.querySelector('.summary-actions'),'내 이야기 공유 ↗',()=>{const p=engine.profile(chart());share('나의 사주 이야기',p.top[0].title);},'summary-reroll');shareButton.id='saiShare';
  const faqs=[
    ['이용','정말 990원인가요?','상품별 정가는 990원입니다. 현재는 테스트 버전이므로 실제 청구는 0원이며 자동결제나 구독은 없습니다.'],
    ['로그인','카카오·네이버·구글 계정이 실제로 연결되나요?','지금은 이 브라우저 안에서만 동작하는 테스트 로그인입니다. 실제 소셜 계정에는 연결하지 않습니다. 마이페이지에서 세 방식의 테스트 연동을 체험할 수 있습니다.'],
    ['무료','오늘의 운세는 몇 번 볼 수 있나요?','로그인 후 매일 한 번 새 운세를 만들고 같은 날에는 결과를 계속 다시 볼 수 있습니다. 한국 시간 자정 기준이며 그날 처음 사용한 출생 정보를 기준으로 보관됩니다.'],
    ['무료','무료 상담은 언제 다시 생기나요?','한국 시간 기준 하루 한 번입니다. 이미 받은 상담은 마이페이지에서 다시 볼 수 있고 다음 날 새로운 상담을 받을 수 있습니다. 현재는 주제별 규칙으로 답하는 테스트 상담입니다.'],
    ['사주','태어난 시간을 몰라도 되나요?','비워두면 시주를 추정하지 않고 나머지 기둥으로 해석합니다. 대운 시작과 배열은 출생 시각 및 대운 계산 기준을 모두 입력해야 볼 수 있습니다.'],
    ['사주','어떻게 해석하나요?','기존 만세력의 네 기둥·지장간·계절·십성·대운을 읽고, 근거가 있는 특징을 선정합니다. 가중치는 서비스의 해석 기준이며 통계적인 사건 확률이나 정통 용신 확정 판정은 아닙니다.'],
    ['구매','구매한 결과는 어디에 있나요?','로그인 후 마이페이지의 구매 보관함에서 볼 수 있습니다. 같은 상품과 같은 분석 조건은 중복 구매하지 않습니다. 테스트 데이터는 브라우저를 바꾸면 이동하지 않습니다.'],
    ['공유','인스타그램에 바로 게시할 수 있나요?','이미지를 만들고 지원 기기의 공유 메뉴를 열 수 있습니다. 직접 게시하는 방식이며, 지원하지 않는 브라우저에서는 이미지 저장과 문장 복사를 제공합니다.'],
    ['개인정보','내 정보는 어디에 저장되나요?','만세력 계산은 브라우저에서 진행됩니다. 로그인한 테스트 계정의 출생 정보·상담·구매 결과는 이 브라우저 저장소에 저장하며, 마이페이지에서 모두 삭제할 수 있습니다.'],
    ['구매','택일 결과는 무엇인가요?','선택한 목적과 최대 90일 기간 안에서 원국과 날짜의 관계를 비교한 후보입니다. 실제 행사 조건을 함께 확인하세요. 동점은 빠른 날짜부터 표시합니다.']
  ];
  if(api.production){
    faqs[0]=['이용','유료 상품을 구매할 수 있나요?','결제는 준비 중이며 사주·궁합·대운·연운·택일 해석은 현재 무료로 제공됩니다.'];
    faqs[1]=['로그인','카카오·네이버 계정이 실제로 연결되나요?','카카오·네이버의 인증 화면에서 로그인합니다. 마이페이지에서 다른 로그인 방식을 내 계정에 연동할 수 있습니다. 운영자의 앱 설정이 완료되어야 이용할 수 있습니다.'];
    faqs[3]=['무료','무료 상담은 언제 다시 생기나요?','한국 시간 기준 하루 한 번입니다. 완성된 상담은 마이페이지에서 다시 볼 수 있습니다. 상담을 받지 못한 경우 횟수는 차감하지 않습니다.'];
    faqs[5]=['사주','어떻게 해석하나요?','만세력은 기존 계산 코드로 산출하고 해석 문장은 AI가 작성합니다. 근거 자료를 함께 전달하지만 AI의 해석은 사실이나 미래 예측이 아닙니다.'];
    faqs[6]=['구매','구매 보관함을 사용할 수 있나요?','결제와 구매 보관함은 준비 중입니다. 무료 해석은 같은 브라우저 세션에서 하루 동안 다시 이용하면 저장된 결과를 보여줍니다.'];
    faqs[8]=['개인정보','내 정보는 어디에 저장되나요?','AI 해석을 요청하면 출생 정보와 질문을 운영자의 맥미니 서버로 전송합니다. 로그인 전 해석 결과도 브라우저 세션별로 최대 하루 보관합니다. 로그인 후 저장한 출생 정보와 상담은 마이페이지에서 계정과 함께 삭제할 수 있습니다.'];
  }
  const faq=el('section','section faq-section');faq.id='faq';faq.innerHTML='<div class="section-head"><span class="kicker">QUESTIONS & ANSWERS</span><h2>궁금한 이야기</h2><p>자주 묻는 질문을 모았어요.</p></div><label class="faq-search">질문 검색<input id="faqSearch" type="search" placeholder="로그인, 무료 상담, 공유…"></label><div class="faq-filters" id="faqFilters"></div><p id="faqCount" role="status"></p><div id="faqList"></div>';
  $('about').before(faq);let filter='전체';const filters=['전체',...new Set(faqs.map(f=>f[0]))];for(const value of filters){const b=button($('faqFilters'),value,()=>{filter=value;drawFAQ();},'chip');b.dataset.filter=value;}
  function drawFAQ(){const q=$('faqSearch').value.trim().toLowerCase(),list=$('faqList');list.replaceChildren();const rows=faqs.filter(f=>(filter==='전체'||f[0]===filter)&&f.join(' ').toLowerCase().includes(q));$('faqCount').textContent=`${rows.length}개의 답변`;for(const [cat,title,answer] of rows){const d=append(list,'details','faq-item');append(d,'summary','',`${title}`);append(d,'p','',answer);}if(!rows.length)append(list,'p','','찾는 답변이 없어요. 다른 검색어로 찾아보세요.');$('faqFilters').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));}
  $('faqSearch').addEventListener('input',drawFAQ);drawFAQ();
  window.SaiVisuals={result(c,year,month){let box=$('personalityStory');if(!box){box=el('div','personality-story');box.id='personalityStory';document.querySelector('.summary-controls').before(box);}box.replaceChildren();const p=engine.profile(c),f=engine.frame(c,year,month);const img=append(box,'img','result-mascot');img.src='./assets/sai-mascot.png';img.alt='내 이야기를 들려주는 사이 토끼';img.width=160;img.height=160;const copy=append(box,'div','personality-copy');append(copy,'span','kicker','YOUR INNER STORY');append(copy,'h3','',p.top[0].title);const badges=append(copy,'div','trait-badges');p.top.forEach(t=>append(badges,'span','trait-badge',`${groups[t.group][0]} ${groups[t.group][1]}`));append(copy,'p','',`${month}월의 주제 · ${f.theme.group}`);
      const bars=append(copy,'div','element-bars');const max=Math.max(...Object.values(c.elements),1);Object.entries(c.elements).forEach(([e,n])=>{const row=append(bars,'span','element-meter');row.setAttribute('aria-label',`${e} ${n}개`);append(row,'b','',e);const track=append(row,'span','meter-track');const fill=append(track,'i','meter-fill');fill.style.width=`${n/max*100}%`;append(row,'small','',String(n));});
    }};
  document.addEventListener('sai:chart',event=>run(async()=>{if(session())await api.saveProfile(event.detail.input);}));
  window.addEventListener('storage',event=>{if(event.key==='sai-demo-v2'){run(()=>{window.currentSajuChart=null;resetVisible();restoreProfile();updateAccount();if(modal.open)modal.close();});}});
  if(!api.production){const recovery=button(faq,'테스트 데이터 초기화',confirmReset,'text-button');recovery.id='resetDemo';}
  if(api.production){services.querySelector('.demo-label').textContent='나를 알아가는 사주 이야기';for(const b of $('productGrid').querySelectorAll('button')){b.querySelector('strong').textContent=b.querySelector('strong').textContent.replace('990원 ','');b.querySelector('.product-arrow').textContent='이야기 펼쳐보기 ↗';}}
  if(startupError)notify(startupError.message);if(api.production&&new URLSearchParams(location.search).has('auth_error'))notify('로그인을 취소하셨습니다.');
  try{updateAccount();restoreProfile();}catch(e){notify(e.message);}
})().catch(e=>console.error(e));
